apiVersion: 1

datasources:
  - name: NOAA GSOM
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    user: admin
    secureJsonData:
      token: ${DB_ADMIN_TOKEN}
    jsonData:
      version: Flux
      organization: ${DB_INIT_ORG}
      defaultBucket: bucket
      tlsSkipVerify: true
    isDefault: true
    editable: true
