version: '3'

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    networks:
      - metrics-network
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - TELEGRAF_PASSWORD=${TELEGRAF_PASSWORD}
      - CLIMATE_PASSWORD=${CLIMATE_PASSWORD}
    volumes:
      - ./influxdb_data:/var/lib/influxdb
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./influxdb/init-influxdb.sh:/docker-entrypoint-initdb.d/init-influxdb.sh

  chronograf:
    image: chronograf:latest
    container_name: chronograf
    restart: always
    depends_on:
      - influxdb
    networks:
      - metrics-network
    ports:
      - '8888:8888'
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: always
    depends_on:
      - influxdb
    networks:
      - metrics-network
    environment:
      - IS_RASPBERRY_PI=${IS_RASPBERRY_PI}
      - TELEGRAF_PASSWORD=${TELEGRAF_PASSWORD}
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    command: ["sh", "-c", "if [ \"$IS_RASPBERRY_PI\" = \"true\" ]; then telegraf; else sleep infinity; fi"]

  grafana:
    image: grafana/grafana:latest
    user: "$UID:$GID"
    container_name: grafana
    restart: always
    depends_on:
      - influxdb
    networks:
      - metrics-network
    ports:
      - '3000:3000'
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini

  climate-data:
    build:
      context: ../
      dockerfile: ./docker/climate_data/Dockerfile
    container_name: climate-data
    restart: always
    depends_on:
      - influxdb
    networks:
      - metrics-network
    volumes:
      - ./docker/climate_data/log:/app/log
    environment:
      - CLIMATE_PASSWORD=${CLIMATE_PASSWORD}
      - NOAA_TOKEN=${NOAA_TOKEN}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "7"

networks:
  metrics-network:
    driver: bridge

volumes:
  grafana_data: { }
  influxdb_data: { }
