{
 "title": "NOAA GSOM Dashboard",
 "time": { "from": "1900-05-03T06:46:58.000Z", "to": "2023-08-26T19:40:10.000Z" },
 "templating": {
  "list": [
   {
    "name": "country_iso",
    "label": "Country ISO",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: \"climate-bucket\", tag: \"country_iso\", start: v.timeRangeStart, stop: v.timeRangeStop)"
   }
  ]
 },
 "panels": [
  {
   "title": "Last Update",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Last Run",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "metadata",
     "query": "from(bucket: \"climate-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metadata\" and r[\"script\"] == \"gsoy_importer\")\r\n  |> last(column: \"last_run\")\r\n",
     "select": [
      [
       { "params": [ "last_run" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "script::tag", "operator": "=", "value": "gsom_fetcher" }
     ]
    }
   ]
  },
  {
   "title": "Number of Countries",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "metadata",
     "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: \"climate-bucket\", tag: \"country_iso\", start: 1700-01-01T00:00:00Z, stop: 3000-12-31T23:59:59Z)\r\n",
     "select": [
      [
       { "params": [ "last_run" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "script::tag", "operator": "=", "value": "gsom_fetcher" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Extreme Temperature Events (yearly)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "alias": "Max: $country_name",
       "groupBy": [
        { "params": [ "365d" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "Extreme_Maximum_Temperature_yearly_average",
       "query": "from(bucket: \"climate-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Extreme_Maximum_Temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"country_iso\"] == \"${country_iso}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _measurement: \"Maximum Temperature\" }))\r\n  |> map(fn: (r) => ({ r with _field: \"\" }))\r\n  |> map(fn: (r) => ({ r with country_iso: \"\" }))\r\n  |> yield(name: \"max\")\r\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "country_id::tag", "operator": "=~", "value": "/^$country_id$/" }
       ]
      },
      {
       "alias": "Min: $country_name",
       "groupBy": [
        { "params": [ "365d" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "Extreme_Minimum_Temperature_yearly_average",
       "query": "from(bucket: \"climate-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Extreme_Minimum_Temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"country_iso\"] == \"${country_iso}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _measurement: \"Minimum Temperature\" }))\r\n  |> map(fn: (r) => ({ r with _field: \"\" }))\r\n  |> map(fn: (r) => ({ r with country_iso: \"\" }))\r\n  |> yield(name: \"min\")",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ]
       ],
       "tags": [
        { "key": "country_id::tag", "operator": "=~", "value": "/^$country_id$/" }
       ]
      }
     ]
    },
    {
     "title": "Temperatures (yearly)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "alias": "Max: $country_name",
       "groupBy": [
        { "params": [ "365d" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "Extreme_Maximum_Temperature_yearly_average",
       "query": "from(bucket: \"climate-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Maximum_Temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"country_iso\"] == \"${country_iso}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _measurement: \"Maximum Temperature\" }))\r\n  |> map(fn: (r) => ({ r with _field: \"\" }))\r\n  |> map(fn: (r) => ({ r with country_iso: \"\" }))\r\n  |> yield(name: \"max\")\r\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "country_id::tag", "operator": "=~", "value": "/^$country_id$/" }
       ]
      },
      {
       "alias": "Min: $country_name",
       "groupBy": [
        { "params": [ "365d" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "Extreme_Minimum_Temperature_yearly_average",
       "query": "from(bucket: \"climate-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Average_Temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"country_iso\"] == \"${country_iso}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _measurement: \"Average Temperature\" }))\r\n  |> map(fn: (r) => ({ r with _field: \"\" }))\r\n  |> map(fn: (r) => ({ r with country_iso: \"\" }))\r\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ]
       ],
       "tags": [
        { "key": "country_id::tag", "operator": "=~", "value": "/^$country_id$/" }
       ]
      },
      {
       "alias": "Min: $country_name",
       "groupBy": [
        { "params": [ "365d" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "Extreme_Minimum_Temperature_yearly_average",
       "query": "from(bucket: \"climate-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Minimum_Temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"country_iso\"] == \"${country_iso}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _measurement: \"Minimum Temperature\" }))\r\n  |> map(fn: (r) => ({ r with _field: \"\" }))\r\n  |> map(fn: (r) => ({ r with country_iso: \"\" }))\r\n  |> yield(name: \"min\")",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ]
       ],
       "tags": [
        { "key": "country_id::tag", "operator": "=~", "value": "/^$country_id$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Precipitation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Precipitation",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "targets": [
      {
       "alias": "Max: $country_name",
       "groupBy": [
        { "params": [ "365d" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "Extreme_Maximum_Temperature_yearly_average",
       "query": "from(bucket: \"climate-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Total_Precipitation\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"country_iso\"] == \"${country_iso}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _measurement: \"Precipitation\" }))\r\n  |> map(fn: (r) => ({ r with _field: \"\" }))\r\n  |> map(fn: (r) => ({ r with country_iso: \"\" }))\r\n  |> yield(name: \"mean\")\r\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "country_id::tag", "operator": "=~", "value": "/^$country_id$/" }
       ]
      }
     ]
    },
    {
     "title": "Extreme Maximum Precipitation",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "targets": [
      {
       "alias": "Max: $country_name",
       "groupBy": [
        { "params": [ "365d" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "Extreme_Maximum_Temperature_yearly_average",
       "query": "from(bucket: \"climate-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Extreme_Maximum_Precipitation\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"country_iso\"] == \"${country_iso}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _measurement: \"Maximum Precipitation\" }))\r\n  |> map(fn: (r) => ({ r with _field: \"\" }))\r\n  |> map(fn: (r) => ({ r with country_iso: \"\" }))\r\n  |> yield(name: \"max\")\r\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "country_id::tag", "operator": "=~", "value": "/^$country_id$/" }
       ]
      }
     ]
    },
    {
     "title": "Days With Thunder",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "d" } },
     "targets": [
      {
       "alias": "Max: $country_name",
       "groupBy": [
        { "params": [ "365d" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "Extreme_Maximum_Temperature_yearly_average",
       "query": "from(bucket: \"climate-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Number_of_Days_with_Thunder\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"country_iso\"] == \"${country_iso}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _measurement: \"Days With Thunder\" }))\r\n  |> map(fn: (r) => ({ r with _field: \"\" }))\r\n  |> map(fn: (r) => ({ r with country_iso: \"\" }))\r\n  |> yield(name: \"mean\")\r\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "country_id::tag", "operator": "=~", "value": "/^$country_id$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Snow",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Snowfall",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "targets": [
      {
       "alias": "Max: $country_name",
       "groupBy": [
        { "params": [ "365d" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "Extreme_Maximum_Temperature_yearly_average",
       "query": "from(bucket: \"climate-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Total_Snowfall\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"country_iso\"] == \"${country_iso}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _measurement: \"Snowfall\" }))\r\n  |> map(fn: (r) => ({ r with _field: \"\" }))\r\n  |> map(fn: (r) => ({ r with country_iso: \"\" }))\r\n  |> yield(name: \"mean\")\r\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "country_id::tag", "operator": "=~", "value": "/^$country_id$/" }
       ]
      }
     ]
    },
    {
     "title": "Highest Daily Snowfall",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "targets": [
      {
       "alias": "Max: $country_name",
       "groupBy": [
        { "params": [ "365d" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "Extreme_Maximum_Temperature_yearly_average",
       "query": "from(bucket: \"climate-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Highest_Daily_Snowfall\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"country_iso\"] == \"${country_iso}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _measurement: \"Highest Daily Snowfall\" }))\r\n  |> map(fn: (r) => ({ r with _field: \"\" }))\r\n  |> map(fn: (r) => ({ r with country_iso: \"\" }))\r\n  |> yield(name: \"max\")\r\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "country_id::tag", "operator": "=~", "value": "/^$country_id$/" }
       ]
      }
     ]
    },
    {
     "title": "Highest Daily Snow Depth",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "targets": [
      {
       "alias": "Max: $country_name",
       "groupBy": [
        { "params": [ "365d" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "Extreme_Maximum_Temperature_yearly_average",
       "query": "from(bucket: \"climate-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Highest_Daily_Snow_Depth\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"country_iso\"] == \"${country_iso}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _measurement: \"Highest Daily Snow Depth\" }))\r\n  |> map(fn: (r) => ({ r with _field: \"\" }))\r\n  |> map(fn: (r) => ({ r with country_iso: \"\" }))\r\n  |> yield(name: \"max\")\r\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "country_id::tag", "operator": "=~", "value": "/^$country_id$/" }
       ]
      }
     ]
    },
    {
     "title": "Days with Snow",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 6, "x": 18, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "d" } },
     "targets": [
      {
       "alias": "Max: $country_name",
       "groupBy": [
        { "params": [ "365d" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "Extreme_Maximum_Temperature_yearly_average",
       "query": "from(bucket: \"climate-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Number_of_Days_with_Snowfall\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"country_iso\"] == \"${country_iso}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _measurement: \"Days with Snowfall\" }))\r\n  |> map(fn: (r) => ({ r with _field: \"\" }))\r\n  |> map(fn: (r) => ({ r with country_iso: \"\" }))\r\n  |> yield(name: \"mean\")\r\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "country_id::tag", "operator": "=~", "value": "/^$country_id$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Evaporation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total Evaporation",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "alias": "Max: $country_name",
     "groupBy": [
      { "params": [ "365d" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "Extreme_Maximum_Temperature_yearly_average",
     "query": "from(bucket: \"climate-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Total_Evaporation\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"country_iso\"] == \"${country_iso}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _measurement: \"Evaporation\" }))\r\n  |> map(fn: (r) => ({ r with _field: \"\" }))\r\n  |> map(fn: (r) => ({ r with country_iso: \"\" }))\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "country_id::tag", "operator": "=~", "value": "/^$country_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Days with Fog",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "alias": "Max: $country_name",
     "groupBy": [
      { "params": [ "365d" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "Extreme_Maximum_Temperature_yearly_average",
     "query": "from(bucket: \"climate-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Number_of_Days_with_Fog\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"country_iso\"] == \"${country_iso}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _measurement: \"Days with Fog\" }))\r\n  |> map(fn: (r) => ({ r with _field: \"\" }))\r\n  |> map(fn: (r) => ({ r with country_iso: \"\" }))\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "country_id::tag", "operator": "=~", "value": "/^$country_id$/" }
     ]
    }
   ]
  }
 ]
}