{
 "title": "NOAA GSOM Dashboard",
 "time": { "from": "1990-01-01T00:00:00.000Z", "to": "2023-06-11T00:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "Country Name",
    "query": "SHOW TAG VALUES WITH KEY = \"country\""
   }
  ]
 },
 "panels": [
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Maximum Temperature (per country)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "aggregations": [
      { "field": "value", "type": "max" }
     ],
     "alias": "Max Temp: [[tag_country]]",
     "fields": "value",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "Maximum Temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country::tag", "operator": "=~", "value": "/^$country$/" }
     ]
    },
    {
     "alias": "Max Average Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Average Temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "max_avg_tmp" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Minimum Temperature (per country)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "aggregations": [
      { "field": "value", "type": "max" }
     ],
     "alias": "Min Temp: [[tag_country]]",
     "fields": "value",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "Minimum Temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country::tag", "operator": "=~", "value": "/^$country$/" }
     ]
    },
    {
     "alias": "Min Average Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Average Temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Temperature (per country)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "aggregations": [
      { "field": "value", "type": "max" }
     ],
     "alias": "Avg Temp: [[tag_country]]",
     "fields": "value",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "Average Temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country::tag", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Temperature",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "aggregations": [
      { "field": "value", "type": "mean" }
     ],
     "alias": "Average temperature: $country",
     "fields": "value",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country_name" ], "type": "tag" }
     ],
     "measurement": "Average Temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country::tag", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Temperature",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "aggregations": [
      { "field": "value", "type": "max" }
     ],
     "alias": "Avg Temp: [[tag_country]]",
     "fields": "value",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "Average Temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country::tag", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Days with Heat Index >= 90F/32.2C",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "alias": "$tag_country_name",
     "fields": "value",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country_name" ], "type": "tag" }
     ],
     "measurement": "Days with Heat Index >= 90F/32.2C",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country::tag", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  { "title": "Water & Evaporation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Precipitation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "alias": "$tag_country_name",
     "fields": "value",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country_name" ], "type": "tag" }
     ],
     "measurement": "Precipitation",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country::tag", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Days with Thunder",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "alias": "$tag_country_name",
     "fields": "value",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country_name" ], "type": "tag" }
     ],
     "measurement": "Days with Thunder",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country::tag", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Relative Humidity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 87 },
   "targets": [
    {
     "alias": "$tag_country_name",
     "fields": "value",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country_name" ], "type": "tag" }
     ],
     "measurement": "Average Relative Humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country::tag", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Snowfall",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 87 },
   "targets": [
    {
     "alias": "$tag_country_name",
     "fields": "value",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country_name" ], "type": "tag" }
     ],
     "measurement": "Snowfall",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country::tag", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Evaporation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 93 },
   "targets": [
    {
     "alias": "$tag_country_name",
     "fields": "value",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country_name" ], "type": "tag" }
     ],
     "measurement": "Evaporation",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country::tag", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Days with Fog",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 93 },
   "targets": [
    {
     "alias": "$tag_country_name",
     "fields": "value",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country_name" ], "type": "tag" }
     ],
     "measurement": "Days with Fog",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country::tag", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  { "title": "Wind", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "Fastest 5-Second Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 100 },
   "targets": [
    {
     "alias": "$tag_country_name",
     "fields": "value",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country_name" ], "type": "tag" }
     ],
     "measurement": "Fastest 5-Second Wind Speed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country::tag", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Fastest 2-Minute Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 100 },
   "targets": [
    {
     "alias": "$tag_country_name",
     "fields": "value",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country_name" ], "type": "tag" }
     ],
     "measurement": "Fastest 2-Minute Wind Speed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country::tag", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Fastest 5-Minute Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 100 },
   "targets": [
    {
     "alias": "$tag_country_name",
     "fields": "value",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country_name" ], "type": "tag" }
     ],
     "measurement": "Fastest 5-Minute Wind Speed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country::tag", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Wind Movement",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 106 },
   "targets": [
    {
     "alias": "$tag_country_name",
     "fields": "value",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country_name" ], "type": "tag" }
     ],
     "measurement": "Wind Movement",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country::tag", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Fastest Instantaneous Wind Speed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 113 },
   "yaxes": [
    { "label": "Wind Speed" }
   ],
   "targets": [
    {
     "alias": "$tag_country_name",
     "fields": "value",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country_name" ], "type": "tag" }
     ],
     "measurement": "Fastest Instantaneous Wind Speed"
    }
   ]
  },
  {
   "title": "Peak Gust Wind Speed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 113 },
   "yaxes": [
    { "label": "Wind Speed" }
   ],
   "targets": [
    {
     "alias": "$tag_country_name",
     "fields": "value",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country_name" ], "type": "tag" }
     ],
     "measurement": "Peak Gust Wind Speed"
    }
   ]
  },
  {
   "title": "Average Daily Wind Speed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 119 },
   "yaxes": [
    { "label": "Wind Speed" }
   ],
   "targets": [
    {
     "alias": "$tag_country_name",
     "fields": "value",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country_name" ], "type": "tag" }
     ],
     "measurement": "Average Daily Wind Speed"
    }
   ]
  }
 ]
}